#file for compiling
FILES = gtu/automation_system_for_cargo_company/AutomationSystemForCargoCompany.java gtu/automation_system_for_cargo_company/DynamicArray.java Test.java Main.java
#G++ compiler
JAVAC = javac

all: $(FILES)	
	$(JAVAC) $(FILES) -Xlint
