#file for compiling
FILES = gtu/automation_system_for_cargo_company/AutomationSystemForCargoCompany.java gtu/automation_system_for_cargo_company/Administrator.java  gtu/automation_system_for_cargo_company/Branch.java gtu/automation_system_for_cargo_company/CompanySystem.java gtu/automation_system_for_cargo_company/Customer.java gtu/automation_system_for_cargo_company/PrintableInConsole.java gtu/automation_system_for_cargo_company/TransportationPersonnel.java gtu/automation_system_for_cargo_company/User.java gtu/automation_system_for_cargo_company/Shipment.java Test.java Main.java
#G++ compiler
JAVAC = javac

all: $(FILES)	
	$(JAVAC) $(FILES) -Xlint
